### ISSUE TITLE
3d models for player, enemies and pills

### ISSUE THREAD

**Issue by dhubber** [dhubber/mazed-up#18]
If we're going to have the 3d perspective pills, we'll need 3d models of all these objects.  If we keep the super minimalistic circles for the player/enemies, these can obviously be spheres.  The pills will be a bit more work.  The electric floors and exit could also be included here but are not essential.

**Comment by Sebeb** [comment]
![partial screenshot 2018-03-21 01 06 41 ooxs4n](https://user-images.githubusercontent.com/7753735/37689273-5f687b5c-2ca4-11e8-91ec-a8f5563a8e8b.png)
I've come up with what I think is quite an elegant solution. Basicaly once first-person mode is entered, each pill shows a sprite which hovers in the air and always faces the player. Since the first-person mode already controls a bit like the old Wolfenstein games, I figured it made sense to just nick their style of 2.5D graphics ; ) 
![partial screenshot 2018-03-21 01 09 49 nbdrje](https://user-images.githubusercontent.com/7753735/37689447-35697a4e-2ca5-11e8-829d-1a3dde7feea5.png)
What do you think? The enemies look interesting like this, but maybe it would be easier to just replace them with spheres. Although it may be more consistent to stick with one style. 
![partial screenshot 2018-03-21 01 23 42 nzf1ci](https://user-images.githubusercontent.com/7753735/37689672-a805d48e-2ca6-11e8-81ae-e8627f2bdb38.png)

**Comment by dhubber** [comment]
Wow wow wow, slow down!  I'm not done with this one yet ;-) .  However, because of the level transition bug I just posted, I can't properly test how this looks (because I'm only ever on the first level).  However, the isometric 3d view looked pretty good so I'm guessing it shouldn't look too bad with the first-person either.

**Comment by Sebeb** [comment]
Yeah, you have to press enter to proceed to the next level haha. Sorry I didn't mention that! I made a little dev menu in the Unity editor to test pills. If you go Dev Option > Dev Menu in unity's top menu, you can spawn pills to your heart's desire

**Comment by dhubber** [comment]
ok, I've finally had the chance to play through many pills and I think it looks absolutely fine if we stick with these minimalistic graphics.  Obviously if we do update them then we can come back to this, but for now I think this is great!  👍

**Comment by Sebeb** [comment]
Honestly, in hindsight I think it would have actually been a lot easier to just switch to 3D models haha. The code to have 3 sprites for each object (top down, isometric and first person sprites) got pretty complicated. I'm happy with the style at the moment though.
