### ISSUE TITLE
Smooth player reset

### ISSUE THREAD

**Issue by Sebeb** [dhubber/mazed-up#31]
Rather than having all effects instantly reset, it could be worth having them smoothly revert over a couple of seconds, where applicable

**Comment by dhubber** [comment]
Are you talking about when a level has finished and the player is starting from zero for the next level, or when the effects sometimes phase in-and-out?  If phasing in-and-out, I guess this only makes sense for visual effects like the pixellation or blurring.  Most others, like reversing controls or rotating the map, just have to happen, like a switch on or off.

Actually on a similar topic (so I'll post it here), I was thinking that some of the effects are 'permanent', like zooming in to the player's location or of course switching to the first-person perspective, which then makes some other pills irrelevant (e.g. First-person makes zooming-in or rotating the map ineffective).  Is this what we really want to happen, since then the accumulative effect of the pills stops and you can even use this to your advantage perhaps and avoid some effects completely.  Although I really like some of these effects, I don't want them to detract from the other (in some ways more interesting) effects and in particular the associated difficulty.

**Comment by Sebeb** [comment]
I was talking about when the player exits the level and everything the pills have changed resets. So of course boolean variables will just have to be instantly toggled. But for example, variables such as pixelation, blurring, and colour phasing (bad trip) could all smoothly transition from whatever state they're in back to vanilla over a couple of seconds. I think I've got another issue open to try and make the first-person camera transition smoothly from third person, so if we get round to implamenting that, it could simply do this again in reverse here.

I've tried to make it so that all pills still have a noticable effect when taken in combination with any other pills. With the first-person pill, pills which effect the normal camera effect your minimap instead. So the zoom pill will make your minimap far less useful, since it now pretty much only displays surroundings you can see in first person anyway.

The rotation pill now works very differently, in that it actually physically rotates the world around the player, which holds effect no matter what the current perspective. At the moment, the player doesn't rotate, which on one hand is a shame, since when normal controls are enabled, up is always forwards, unlike before when forwards would rotate along with the maze (since the maze wasn't acutally rotating, just the camera.) But this had to be done to be compatible so that the world still seems to rotate in first person.

Since tank controls are enabled in first person anyway, I've also made it so that picking up the tank pill in first person now rotates your minimap to the direction the player's facing. I figured we can allow the player one, single, positive synergy :stuck_out_tongue_winking_eye:

Before I was using a blacklist system, in which each pill could specify a list of pills which can't be spawned in the same level (for example, no zoom, or tank pills when the first-person pill has been spawned and vice versa.) But I think I've managed to figure out a way for every pill to make a noticable change to gameplay, no matter what combination of pills the player has already picked up, so I'm not using that system anymore. But it is still there, in case we add any pills which simply can't be made to be compatible with every other pill's effect.

Anyway, that's a lot of what I've been working on recently haha. Penny for your thoughts?
